# Generated by Django 5.1.2 on 2024-10-17 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo_curso', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('ciclo', models.IntegerField()),
                ('pre_requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_requeridos', to='estudiantes.curso')),
            ],
            options={
                'ordering': ['nivel', 'ciclo', 'codigo_curso'],
            },
        ),
        migrations.CreateModel(
            name='CursoAprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_aprobados', to='estudiantes.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_aprobados', to='usuarios.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
