# Generated by Django 5.0.1 on 2024-10-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('usuarios', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=4)),
                ('celular', models.CharField(max_length=9)),
                ('num_recibo_primero', models.CharField(max_length=20)),
                ('num_recibo_segundo', models.CharField(max_length=20)),
                ('monto_recibo_primero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recibo_segundo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('semestre1', models.ManyToManyField(related_name='matriculas_semestre1', to='estudiantes.curso')),
                ('semestre2', models.ManyToManyField(related_name='matriculas_semestre2', to='estudiantes.curso')),
            ],
        ),
    ]
