# Generated by Django 5.1.2 on 2024-10-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
    ]
