# Generated by Django 5.1.2 on 2024-10-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_matricula_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_pago_1', models.URLField(blank=True, max_length=500, null=True)),
                ('recibo_pago_2', models.URLField(blank=True, max_length=500, null=True)),
                ('boleta_notas', models.URLField(blank=True, max_length=500, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.matricula')),
            ],
        ),
    ]
