# Generated by Django 5.1.2 on 2024-10-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_documentosmatricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosmatricula',
            name='boleta_notas',
            field=models.FileField(default='default.pdf', upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documentosmatricula',
            name='matricula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.matricula'),
        ),
        migrations.AlterField(
            model_name='documentosmatricula',
            name='recibo_pago_1',
            field=models.FileField(default='default.pdf', upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documentosmatricula',
            name='recibo_pago_2',
            field=models.FileField(default='default.pdf', upload_to='documentos/'),
        ),
    ]
