# Generated by Django 5.0.1 on 2024-10-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_alter_documentosmatricula_boleta_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='vacantes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
